### PR TITLE
Disable SourceSqlInstance mandatory, disable SourceSqlInstance checks…

### PR DESCRIPTION
**Pull request by KazgunovAG**
Workaround for last comment in #90 
Provides more flexibility, when dealing with existing bak files.

### CODE REVIEW

**Comment by sanderstad** [comment]
Can you provide a screenshot that this is working?

**Comment by KazgunovAG** [comment]
Yes:
Screenshot_4
Test script:
```
New-DbaDatabase -SqlInstance lab-dbacln-01-c -Name sample1;
$bak = Backup-DbaDatabase -SqlInstance lab-dbacln-01-c -Database sample1 -Path \\lab-dbacln-01-c\dbaclone\images\ -Type Full;
New-DcnImage -DestinationSqlInstance lab-dbacln-01-c `
             -Database sample1 `
             -ImageNetworkPath \\lab-dbacln-01-c\dbaclone\images\ `
             -BackupFilePath $bak.BackupPath `
             -Verbose;
```
But, I made one more fix, after pull request:
Screenshot_5
Without it we loosing database name in image's filename.

**Comment by sanderstad** [comment]
That looks very good.

Thank you

**Comment by KazgunovAG** [comment]
Please! And thank you for this useful tool)

**Pull request merged**
