### PR TITLE
New-DcnClone: use dbatools for db enumeration

### LINKED ISSUE #216: New-DcnClone: Enumerating databases triggers error
**Before submitting the bug**
- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

**Describe the bug**
When enumerating databases in SMO with other clones being created simultaneously, sometimes the verifying block encounters an error.

https://github.com/dataplat/dbaclone/blob/1bf77597166f86a7ce741984d40fab8f54b73e5c/functions/clone/New-DcnClone.ps1#L361-L363

Which spits out:

> VERBOSE: Performing the operation "Verifying database existence" on target "database-a".
>   Unable to create database [database-a]: The following exception occurred while trying to enumerate the collection: "Database 'database-b' is in transition. Try the statement later.".

I believe switching in the more robust `Get-DbaDatabase` command may be a quick solve here.

### PR DESCRIPTION
**Pull request by lowlydba**
Fixes #216

### CODE REVIEW

**Review by sanderstad — COMMENTED** [review]
I wonder if that is something we want to do. We already have the server object which already contains all the database objects.
Using Get-DbaDatabase opens another connection to the database server which in theory isn't needed

**Comment by lowlydba** [comment]
> I wonder if that is something we want to do. We already have the server object which already contains all the database objects. Using Get-DbaDatabase opens another connection to the database server which in theory isn't needed

Could definitely to it custom, but the DBA tools function does a lot of heavy lifting to ensure it doesn't error out, so re-doing that work might not be worth it.

**Comment by sanderstad** [comment]
> > I wonder if that is something we want to do. We already have the server object which already contains all the database objects. Using Get-DbaDatabase opens another connection to the database server which in theory isn't needed
> 
> Could definitely to it custom, but the DBA tools function does a lot of heavy lifting to ensure it doesn't error out, so re-doing that work might not be worth it.

Good call. If I write my script and already have a connections I try to refrain from having multiple connections because when you're iterating lots and lots of objects, then those connections  can really add up.

In this case I think it could be benefitial.

**Review by sanderstad — APPROVED** [review]

**Comment by sanderstad** [comment]
Thank you for putting in the effort

**Pull request merged**
